### ISSUE TITLE
Override Default Behavior for Adhoc Queries

### ISSUE THREAD

**Issue by twoxfh** [ssharish/jrest#1]
For Pull requests, can you have a dynamic set of fields, specifically for the SQL where clause in the case of adhoc queries? Is there a recommend approach for this? If not supported, what would be your approach? I was thinking a before method could override the query definition and use a string builder for creating adhoc queries. It would also be nice to inject the username for insert/update queries. 

Thoughts?

**Comment by ssharish** [comment]
Could you please provide examples to the usecases you are stating?  I was considering to add an adhoc URI so that SQL and its parameters could be provided dynamically; would that help?

**Comment by twoxfh** [comment]
For example a movie database with movie title, year, genre, rating, etc. You can have a screen that has all the inputs but the user may select one or multiple to search on. So movie title with operator like and value the matrix can be searched. Optionally you can add year, ratinf, etc.

Ideally all URI's would have json schema validation for the jsondata submitted for the jrestKey. For example the json schema would have a field json object with operator and value. Operator would be an enum of values for the field type(eg and, or, like) and value would have constraints (eg regex, max,min) then combine that with the before and after method you can implement a wider range of use cases with validation. A URI might be needed for browsers to get the json schema for client validation before submitting.

I'm not sure a new adhoc URI is needed since the pull URI is mostly for queries. An override of the jrestKey query might be simpler in the before method but either way it would be a nice feature.

**Comment by ssharish** [comment]
After much of pondering on the design I have decided to add /adhoc/pull and /adhoc/pull as new URIs to JRest.  This should meet all your requirements and not change any compiled objects permanently.  Its nice thought, thanks a lot for help in adding this feature to jrest. New drop will be available in couple of days, the code is undergoing usual regression test for the new feature.  I will drop a comment here when I do the checkin, so that you get the intimation.

**Comment by twoxfh** [comment]
Thanks, for putting it together. If it helps any, I mocked a JSON schema for where queries which may be useful. You can use Json Faker to generate a sample of data that could come through.  May or may
 not be useful.

Schema:
```

{
   "$schema":"http://json-schema.org/draft-04/schema#",
   "title":"Sample Where Query Schema for JSON config file",
   "description":"Validates String, Number, Date, NumberIDs, StringIDs",

   "type": "object",
   "properties": {
     "where": {
       "type": "object",
       "properties": {
         "field1": { "$ref": "#/definitions/string"},
         "field2": { "$ref": "#/definitions/number" },
         "field3": { "$ref": "#/definitions/date" },
         "field4": { "$ref": "#/definitions/numberid" },
         "field5": { "$ref": "#/definitions/stringid" }
       },
    "anyOf": [
        {"required": ["field1"]},
        {"required": ["field2"]},
        {"required": ["field3"]},
        {"required": ["field4"]},
        {"required": ["field5"]}
    ]
     },
"order":{
  "type":"object",
  "properties":{
       "type":{ "type": "string",
           "enum": ["ASC","DESC"]},

  "fields":{
 "type": "array",
 "maxItems": 2,
 "items": {
           "type": "string",
           "enum": ["field1","field2","field3","field4","field5"]
          },
  
       "required": ["items"]
     }},
       "required": ["type", "fields"]
},

     "limit":{"enum":[10,20,50],"type":"number","default": "10"},
	 "page":{"type":"number","minimum": 0,
            "maximum": 999,"default": "0"}
   },
       "required": ["where", "limit","page"]
    ,
   "definitions": {
     "string": {
       "type": "object",
       "properties": {
         "operator": {"enum": ["=","like"] },
         "value": { "type": "string",
         "maxLength": 10,
         "minLength": 1,
         "pattern": "^[a-zA-Z0-9]+$"}
       },
       "required": ["operator", "value"]
     },
      "number": {
       "type": "object",
       "properties": {
         "operator": {"enum": [">","<","="] },
         "value": { "type": "number",
            "minimum": 0,
            "maximum": 999999999999 }
       },
       "required": ["operator", "value"]
     },
      "numberid": {
       "type": "object",
       "properties": {
         "operator": {"enum": ["in"] },
              "value": {
 "type": "array",
 "maxItems": 20,
 "items": {
           "type": "number",
           "minimum": 0,
            "maximum": 9999999999
          },
  
       "required": ["items"]
     }
       },
       "required": ["operator", "value"]
     },
      "stringid": {
       "type": "object",
       "properties": {
         "operator": {"enum": ["in"] },
              "value": {
 "type": "array",
 "maxItems": 20,
 "items": {
           "type": "string",
         "maxLength": 10,
         "minLength": 1,
         "pattern": "^[a-zA-Z0-9]+$"
          },
  
       "required": ["items"]
     }
       },
       "required": ["operator", "value"]
     },
      "date": {
       "type": "object",
       "properties": {
         "operator": {"enum": ["between"], "maxDays":"365" },
         "value": { "type": "string", "format": "date-time"},
         "value2": { "type": "string", "format": "date-time" }

       },
       "required": ["operator", "value", "value2"]
     }
   }
}

```

**Comment by ssharish** [comment]
New drop is available now, hope it helps.

**Comment by twoxfh** [comment]
Thanks.. much quicker for developing/debugging.
