### ISSUE TITLE
Upload/Download capability

### ISSUE THREAD

**Issue by twoxfh** [ssharish/jrest#2]
Exceptions and Constants classes list valid access types as Get, Set, Upload, and Download. Javadoc.xml mentions org.milkyway.jrest.upload and org.milkyway.jrest.download but I cannot find these directories. I also do not see any documentation on how to use upload or download.

**Comment by ssharish** [comment]
We had designed both these URIs for our own use in one of the large scale project we were involved with.  Below is the signature for the implementation.

```
Response executeUpload(@HeaderParam(Constants.SESSION_KEY) String sessionKey,
	  @HeaderParam(Constants.JREST_KEY) String jrestKey,
	  @DefaultValue(Constants.NULL) @HeaderParam(Constants.gsFileName) String fileName,
	  @FormDataParam(Constants.gsFile) InputStream fileStream,
	  @FormDataParam(Constants.gsFile) FormDataContentDisposition fileDetails)
```

Issue with this was firstly securing the URIs were difficult and secondly providing fileStream as part of the API was ok with a code making call to JRest but not from any scripting libraries.  So we removed them from public release.  Unlike rest of the system we could not make file upload/download simple and secure.  It is probably better to stick with standard implementation on this aspect.  Thank you for point this out I will remove the references from the code base.
